### ISSUE TITLE
Index name for generation units

### ISSUE THREAD

**Issue by erikfilias** [openENTRANCE/nomenclature#101]
This post tries to introduce the dilemma of index names for generation units. We typically have several generator units per node belonging to the same type of technologies and different characteristics or several groups per generator unit or power plant in power system optimization problems.
In the openTEPES model, we use a name per generator unit as an identifier, and we need to introduce it in the nomenclature.
Actually, we have variables in nomenclature like:

`Maximum Active Power|Electricity|<Fuel>:`

And, we need something like:

`Maximum Active Power|Electricity|<Fuel>|<Name>:`

We would like to know if someone has the same need in order to prepare a common proposal. 
If that's the case, comment, please.

Any opinion?
@openENTRANCE/modellers

**Comment by sandrinecharousset** [comment]
In plan4eu we do not use the names of units (even if we could), mainly because when simulating datasets for 2050, we have no idea of those names. Moreover, we do not have access to detailed data per unit, but data per 'kinds of units' (in general per technology, which could be refined compared to the list of technologies today available in the nomenclature)
In the end, we generate names for each units, which are built like: Zone-Technology_index , and we are using the variable Number of Units|Electricity|<Fuel> to state how many of those units are existing
In the end we will eg have:
France-Nuclear_0, France-Nuclear_1..... Spain-Wind|Offshore_0
And if we would need to refine we could have
France-Nuclear|1600_0, France-Nuclear|800_0...
It is usefull for post-optimisation calculations, eg when we want outputs per technology, per groups of technologies, per sub-groups of technologies....
I am sure this rule can be improved.....
Of course, in the models that are doing the operational optimisation in EDF, names of units are used (because we need to know this schedule is for this specific plant), but I don't really see any need (nor potential use) for prospective studies.

**Comment by erikfilias** [comment]
> In plan4eu we do not use the names of units (even if we could), mainly because when simulating datasets for 2050, we have no idea of those names. Moreover, we do not have access to detailed data per unit, but data per 'kinds of units' (in general per technology, which could be refined compared to the list of technologies today available in the nomenclature)
> In the end, we generate names for each units, which are built like: Zone-Technology_index , and we are using the variable Number of Units|Electricity| to state how many of those units are existing
> In the end we will eg have:
> France-Nuclear_0, France-Nuclear_1..... Spain-Wind|Offshore_0
> And if we would need to refine we could have
> France-Nuclear|1600_0, France-Nuclear|800_0...
> It is usefull for post-optimisation calculations, eg when we want outputs per technology, per groups of technologies, per sub-groups of technologies....
> I am sure this rule can be improved.....
> Of course, in the models that are doing the operational optimisation in EDF, names of units are used (because we need to know this schedule is for this specific plant), but I don't really see any need (nor potential use) for prospective studies.

Thank you @sandrinecharousset! I see your point, and it is suitable. If nobody has any additional comments, I'll close this issue.
