### ISSUE TITLE
Country names differ between nomenclature and Scenario explorer

### ISSUE THREAD

**Issue by HauHe** [openENTRANCE/nomenclature#121]
Hi,
when working with the nomenclature and the IIASA scenario explorer, I noticed that when using the nomenclature to convert ISO codes to country names, `SK` is converted to `Slovakia` and `NL` to `The Netherlands`. However, when the trying to upload the data to the scenario explorer one gets an error since the scenario explorer expects `Slovak Republic`and `Netherlands`.

**Comment by HauHe** [comment]
In my dataset I had the countries of the EU28, Norway and Switzerland. 
I don't know if there are similiar issues with other countries.

**Comment by willu47** [comment]
(it would be good if the Scenario Explorer supported ISO codes and automatically transformed them). @danielhuppmann - is there a public repo for the Scenario Explorer I could make an issue on?

**Comment by danielhuppmann** [comment]
Thanks @HauHe for spotting this inconsistency, I'll fix this.

@willu47, we're working on an easily configurable "rename-during-upload" feature, which can then be configured as part of this repo (so that a modeling team can specify "we upload ISO, please rename to full country name and also aggregate from national to EU, ..."). This is to be deployed this month.

We can also work on a feature to display alternative region names in a Scenario Explorer instance, I'll put that on our internal to-do list (and there is a Feedback button in every Scenario Explorer instance for these kind of suggestions).

**Comment by danielhuppmann** [comment]
@HauHe, I fixed the names of the two country in the ECEMF-internal database backend - luckily, this was not an inconsistency in this repo required.

I also re-triggered your failed upload from yesterday (impersonating your user, so you should have received two notifications from our scenario processing service).

**Comment by HauHe** [comment]
Thanks for fixing this @danielhuppmann !
Yes, I got the notifications.
