### ISSUE TITLE
Review variables/units and add relevant nomenclature for `plan4EU` model

### ISSUE THREAD

**Issue by danielhuppmann** [openENTRANCE/nomenclature#6]
This will review the first set of variables/units and add a list of variables relevant for the `plan4EU` model. It should not add (at this stage) all required variables (to not have a PR too large to review), but rather see whether the process for adding variables and units is sufficiently simple and intuitive.

depends on #4

**Comment by sandrinecharousset** [comment]
About the Energy/Energy-final variables:
I find a bit ambiguous the way some variables are described. eg: 
Final Energy|Industry|Electricity:
   description: Final energy consumption by the industrial sector of electricity (including on-site solar pv), excluding transmission/distribution losses => I asked myself when reading that 'what is the industrial sector of electricity? => I Believe what is mentioned here is the electricity consumption of the industrial sector? Not the final Energy needs of the electrcity industry sector…. If yes I would change the order of the sentence:
electricity share in the final Energy consumption of the industrial sector or something like that… (not completely sure…) 
The same comment applies to all Final Energy|Industry|*  where it may be ambiguous as there exist industries that produce the final Energy which is described. (and even to others such as Final Energy|residential and Commercial|electricity, because there exist residentials that produce electricity….. but I admit this would require a Strange brain….

Final Energy|Non-Energy Use : the description is "Final energy consumption by the non-combustion processes" : I am not completely sure to understand what that means : does it refer to Something (eg biomass) that is used to produce eg food? (Something not related to Energy)

**Comment by sandrinecharousset** [comment]
@danielhuppmann sorry forgot to mention you in the comment above. Did not use pull request as I am not sure of the change I would require.....

**Comment by danielhuppmann** [comment]
thanks @sandrinecharousset for these comments!

> Final Energy|Industry|Electricity

You are right, this formulation is confusing. It should probably be just changed to "Total electricity consumption of industry"

> Final Energy|Industry

This should include only industry sectors that do not produce energy. The own consumption of the electricity sector, for example, should be covered by the difference between primary-energy input and secondary-energy output.

> Final Energy|Non-Energy Use

I would interpret this as all consumption of fuels that were previously considered primary/secondary energy carriers. So crude oil that is used for plastics - yes. Biomass that is used for food - no.

Hope this helps and is enough to start a PR with suggested changes.

**Comment by sandrinecharousset** [comment]
@danielhuppmann is thank you! Will do the PR once we have clarified the way of using branches and forks........
