### ISSUE TITLE
Validation fails on directional data

### ISSUE THREAD

**Issue by danielhuppmann** [openENTRANCE/nomenclature#60]
The current `validate()`function fails on any data using directional region definitions (i.e., `Region A>Region B`).

Reported by @sandrinecharousset

**Comment by danielhuppmann** [comment]
Follow-up question: do we want to enforce that directional data can only be at the same hierarchical level. E.g., NUTS3 can only go to another NUTS3 region? Or is any combination of region-hierarchy levels valid?

**Comment by sebastianzwickl** [comment]
Although any restriction might reduce the flexibility of the modeler, I am in favor of restriction between equal hierarchical levels.

**Comment by sandrinecharousset** [comment]
In plan4eu we need transmission lines between regions of different levels. This is needed because we model eg France and Germany at level of ehighway clusters and other countries at country level except some that are aggregated in bigger regions
We have then lines between eg france|cluster 14 and Spain...

**Comment by danielhuppmann** [comment]
understood @sandrinecharousset - so let's go with the any-combination-works approach. This will make selection in the Scenario Explorer a bit cumbersome because of thousands of possible combination, but we'll see if we can implement something to simplify this...
