### ISSUE TITLE
Mean Outage Duration - share or time?

### ISSUE THREAD

**Issue by danielhuppmann** [openENTRANCE/nomenclature#98]
While restructuring the variables related to power plants, I noticed that the variable "Mean Outage Duration" is given as % rather than a time (hour, seconds). Is there a particular reason? Or if this should be given as a percentage, then what is the base from the share is computed?

PS. This question also applies (to some extend) to "Forced Outage Rate" and "Planned Outage Rate"...

https://github.com/openENTRANCE/nomenclature/blob/cefbaf0bdd8afaf1b574a9dc69f6c48881b1e793/nomenclature/definitions/variable/technology/power-plant.yaml#L65

**Comment by danielhuppmann** [comment]
@sandrinecharousset @erikfilias @tburandt - any thoughts?

**Comment by tburandt** [comment]
In some of the power system models I worked with, also percentages have been used. Therefore, I am actually fine with using percentages instead of time.

**Comment by sandrinecharousset** [comment]
For the duration it is a mistake, this is typically expressed in number of days
For the forced outage and planned outage it is a percentage of the maxpower (usually a figure between 0 and 1, in most cases 0 - meaning plant is anavailable, or 1, meaning it is fully available, while eg 0.5 means it is available but due to some reasons, maxpoiwer has ot be reduced by 50%). We would write share of MaxPower but would not be completely true as this will also impacts eg MinPower (eg if the plant is 0% available then MinPower=0, but if the plant is 50% available with MaxPower=1000 and MinPower=100, then it means the new MaxPower is 500 while the new MinPower is still 100 ; another trick case, if original MinPower=900 and MaxPower=1000, then 50% availability means MinPower=MaxPower=0 (because it would mean MaxPower=500, MinPower=900 .....)

**Comment by erikfilias** [comment]
> For the duration it is a mistake, this is typically expressed in number of days
> For the forced outage and planned outage it is a percentage of the maxpower (usually a figure between 0 and 1, in most cases 0 - meaning plant is anavailable, or 1, meaning it is fully available, while eg 0.5 means it is available but due to some reasons, maxpoiwer has ot be reduced by 50%). We would write share of MaxPower but would not be completely true as this will also impacts eg MinPower (eg if the plant is 0% available then MinPower=0, but if the plant is 50% available with MaxPower=1000 and MinPower=100, then it means the new MaxPower is 500 while the new MinPower is still 100 ; another trick case, if original MinPower=900 and MaxPower=1000, then 50% availability means MinPower=MaxPower=0 (because it would mean MaxPower=500, MinPower=900 .....)

I also agree with Sandrine's comment. Usually, the duration is expressed in the time-domain (i.e., hours, days).

**Comment by danielhuppmann** [comment]
Thanks for the explanation. One follow-up question: should we also distinguish the outage duration between planned vs. forced outages, and will we want to also exchange information on minimum/maximum outage duration?

**Comment by sandrinecharousset** [comment]
Yes in principle we could distinguish the outage duration between planned/forced outages; in the real life, I don't have any data with duration for forced or planned outage but maybe in the future.... (just to complement, those are 'statistics' data, mean duration as well as outages rates are used to generate stochastic series of outages.
If we want to be more exhaustive, I would be in favour of having mean forced outage duration / mean planned outage duration (but in real life would fill them with the same values....)
regarding min/max outage duration, I wouldn't know how to use them, and I do not have data neither... so maybe it is not very usefull (except if someone has sth more?)
@erikfilias what do you think?

**Comment by erikfilias** [comment]
> Yes in principle we could distinguish the outage duration between planned/forced outages; in the real life, I don't have any data with duration for forced or planned outage but maybe in the future.... (just to complement, those are 'statistics' data, mean duration as well as outages rates are used to generate stochastic series of outages.
> If we want to be more exhaustive, I would be in favour of having mean forced outage duration / mean planned outage duration (but in real life would fill them with the same values....)
> regarding min/max outage duration, I wouldn't know how to use them, and I do not have data neither... so maybe it is not very usefull (except if someone has sth more?)
> @erikfilias what do you think?

I also agree with Sandrine, but from my perspective, all these parameters are usually needed in reliability analysis that sometimes is included in the unit commitment problem. Likewise, if we need this data, a pre-processing of ENTSOE data [(link)](https://transparency.entsoe.eu/outage-domain/r2/unavailabilityOfProductionAndGenerationUnits/show?name=&defaultValue=false&viewType=TABLE&areaType=CTA&atch=false&dateTime.dateTime=04.02.2021+00:00|UTC|DAY&dateTime.endDateTime=04.02.2022+00:00|UTC|DAY&CTY|10YES-REE------0|MULTI=CTY|10YES-REE------0|MULTI&area.values=CTY|10YES-REE------0!CTA|10YES-REE------0&assetType.values=PU&assetType.values=GU&outageType.values=A54&outageType.values=A53&outageStatus.values=A05&masterDataFilterName=&masterDataFilterCode=&dv-datatable_length=10) could be made. Regarding min/max outage duration, I also prefer to use mean duration because it is an estimation. But for the openTEPES model, we won't need any of these parameters; @arght, please correct me if I am wrong. However, other additional models like EMPS-W (@SarahYS ) or EMPIRE (@stianbacke, @Rezaahang ) could need it. Thus, as a first agreement, we could include the respective variables for planned & forced outages rate and mean outage duration I think.
